import streamlit as st
import google.generativeai as genai

# Page Setup
st.set_page_config(page_title="Mera AI Prompt & Image Builder")
st.title("🎨 Mera Free AI Prompt & Image Builder")
st.write("Apna idea likhein, Gemini prompt banayega aur AI image generate karega!")

# API Key Section
api_key_input = st.text_input("Apni Gemini API Key yahan paste karein:", type="password")

if api_key_input:
    # Key se extra spaces hatana (Fix common error)
    api_key = api_key_input.strip()
    
    # Gemini Setup
    try:
        genai.configure(api_key=api_key)
        # Hum sabse common model use karenge jo kabhi fail nahi hota
        model = genai.GenerativeModel('gemini-pro')
        
        # User Input
        user_topic = st.text_input("Kis cheez ki image banani hai? (English mein likhein)", placeholder="e.g., A cyberpunk cat in rain")
        
        if st.button("Generate Magic ✨"):
            if user_topic:
                with st.spinner('Rukiye! Gemini prompt likh raha hai...'):
                    # 1. Prompt Generation Logic
                    prompt_request = f"""
                    Act as an expert Midjourney and Stable Diffusion prompt engineer.
                    Write a detailed, creative, and high-quality image generation prompt for the following idea: "{user_topic}".
                    Only give me the prompt text, no explanation.
                    """
                    response = model.generate_content(prompt_request)
                    final_prompt = response.text
                    
                # Show Prompt
                st.success("✅ Prompt Tayyar Hai:")
                st.code(final_prompt)
                
                # 2. Image Generation Logic
                st.write("### 🖼️ Apki Image:")
                with st.spinner('Image download ho rahi hai...'):
                    clean_prompt = final_prompt.replace("\n", " ").strip()
                    image_url = f"https://image.pollinations.ai/prompt/{clean_prompt}?width=1024&height=1024&nologo=true"
                    
                    st.image(image_url, caption="Generated by Pollinations AI")
                    st.write(f"[Download Image]({image_url})")
            else:
                st.warning("Pehle kuch likhein to sahi!")
                
    except Exception as e:
        st.error(f"Error aaya hai: {e}. \nCheck karein ke API Key sahi copy hui hai ya nahi.")
else:
    st.info("Shuru karne ke liye upar apni Gemini API key dalein.")
